"""Add grade_fees and transaction.student_id

Revision ID: e330899e43b3
Revises: f83f199e9585
Create Date: 2026-07-02 13:41:57.816048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e330899e43b3'
down_revision = 'f83f199e9585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_band', sa.String(length=40), nullable=False),
    sa.Column('tuition_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_fees_grade_band'), ['grade_band'], unique=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('grade_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_fees_grade_band'))

    op.drop_table('grade_fees')
    # ### end Alembic commands ###
