"""Add students table

Revision ID: f83f199e9585
Revises: a1a0a53f62f2
Create Date: 2026-07-02 13:21:26.211781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f199e9585'
down_revision = 'a1a0a53f62f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('class_name', sa.String(length=80), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_phone', sa.String(length=40), nullable=True),
    sa.Column('student_no', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_is_active'))
        batch_op.drop_index(batch_op.f('ix_students_full_name'))

    op.drop_table('students')
    # ### end Alembic commands ###
